In [1]:
from elasticsearch import Elasticsearch
import json
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta
from dotenv import load_dotenv 
import os
load_dotenv()

from datavisualization import Docker, Postgres

/Users/liguanwei/Github/HIS-ELK-weekly-report/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:
# docker_cpu = Docker.DockerCPU()
# docker_cpu.prepare_plot()
# docker_cpu.show_plot()
# docker_cpu.save_plot()

In [3]:
postgreslongquery = Postgres.PostgresLongQuery()
postgreslongquery.get_dataframe()

/Users/liguanwei/Github/HIS-ELK-weekly-report/.venv/lib/python3.9/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://192.168.101.11:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(
/Users/liguanwei/Github/HIS-ELK-weekly-report/.venv/lib/python3.9/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.101.11'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,postgresql.log.query_name,event.category,elastic_agent.version,host.os.name.text,host.hostname,process.pid,host.mac,container.id,host.os.version,postgresql.log.sql_state_code,...,host.os.platform,event.type,log.file.path,data_stream.dataset,postgresql.log.client_port,agent.ephemeral_id,event.dataset,user.name.text,log.flags,postgresql.log.detail
0,[<unnamed>],[database],[8.8.2],[Debian GNU/Linux],[histesting],[47948],"[02-42-46-2E-39-BD, 02-42-BC-54-9B-CD, 72-9C-5...",[hisdeploy_postgres_logs],[12 (bookworm)],[00000],...,[debian],[info],[/var/lib/docker/volumes/hisdeploy_postgres_lo...,[postgresql.log],[51141],[348607b3-4734-42dc-b466-dcea2c8951c5],[postgresql.log],[postgres],NaN,NaN
1,[<unnamed>],[database],[8.8.2],[Debian GNU/Linux],[histesting],[47929],"[02-42-46-2E-39-BD, 02-42-BC-54-9B-CD, 72-9C-5...",[hisdeploy_postgres_logs],[12 (bookworm)],[00000],...,[debian],[info],[/var/lib/docker/volumes/hisdeploy_postgres_lo...,[postgresql.log],[51079],[348607b3-4734-42dc-b466-dcea2c8951c5],[postgresql.log],[postgres],NaN,NaN
2,NaN,[database],[8.8.2],[Debian GNU/Linux],[histesting],[55],"[02-42-46-2E-39-BD, 02-42-BC-54-9B-CD, 72-9C-5...",[hisdeploy_postgres_logs],[12 (bookworm)],[00000],...,[debian],[info],[/var/lib/docker/volumes/hisdeploy_postgres_lo...,[postgresql.log],[47308],[348607b3-4734-42dc-b466-dcea2c8951c5],[postgresql.log],[aston],NaN,NaN
3,NaN,[database],[8.8.2],[Debian GNU/Linux],[histesting],[56],"[02-42-46-2E-39-BD, 02-42-BC-54-9B-CD, 72-9C-5...",[hisdeploy_postgres_logs],[12 (bookworm)],[00000],...,[debian],[info],[/var/lib/docker/volumes/hisdeploy_postgres_lo...,[postgresql.log],[47316],[348607b3-4734-42dc-b466-dcea2c8951c5],[postgresql.log],[aston],NaN,NaN
4,[<unnamed>],[database],[8.8.2],[Debian GNU/Linux],[histesting],[47901],"[02-42-46-2E-39-BD, 02-42-BC-54-9B-CD, 72-9C-5...",[hisdeploy_postgres_logs],[12 (bookworm)],[00000],...,[debian],[info],[/var/lib/docker/volumes/hisdeploy_postgres_lo...,[postgresql.log],[56584],[348607b3-4734-42dc-b466-dcea2c8951c5],[postgresql.log],[postgres],[multiline],"[parameters: $1 = '0004000.00010101', $2 = '91..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,[<unnamed>],[database],[8.8.2],[Debian GNU/Linux],[histesting],[11461],"[02-42-46-2E-39-BD, 02-42-BC-54-9B-CD, 72-9C-5...",[hisdeploy_postgres_logs],[12 (bookworm)],[00000],...,[debian],[info],[/var/lib/docker/volumes/hisdeploy_postgres_lo...,[postgresql.log],[40128],[519313de-c266-4364-9197-6e99753b7294],[postgresql.log],[postgres],NaN,[parameters: $1 = '5674646']
592,[<unnamed>],[database],[8.8.2],[Debian GNU/Linux],[histesting],[11461],"[02-42-46-2E-39-BD, 02-42-BC-54-9B-CD, 72-9C-5...",[hisdeploy_postgres_logs],[12 (bookworm)],[00000],...,[debian],[info],[/var/lib/docker/volumes/hisdeploy_postgres_lo...,[postgresql.log],[40128],[519313de-c266-4364-9197-6e99753b7294],[postgresql.log],[postgres],NaN,[parameters: $1 = '1128963']
593,[<unnamed>],[database],[8.8.2],[Debian GNU/Linux],[histesting],[11461],"[02-42-46-2E-39-BD, 02-42-BC-54-9B-CD, 72-9C-5...",[hisdeploy_postgres_logs],[12 (bookworm)],[00000],...,[debian],[info],[/var/lib/docker/volumes/hisdeploy_postgres_lo...,[postgresql.log],[40128],[519313de-c266-4364-9197-6e99753b7294],[postgresql.log],[postgres],NaN,[parameters: $1 = '166666']
594,[<unnamed>],[database],[8.8.2],[Debian GNU/Linux],[histesting],[11462],"[02-42-46-2E-39-BD, 02-42-BC-54-9B-CD, 72-9C-5...",[hisdeploy_postgres_logs],[12 (bookworm)],[00000],...,[debian],[info],[/var/lib/docker/volumes/hisdeploy_postgres_lo...,[postgresql.log],[40138],[519313de-c266-4364-9197-6e99753b7294],[postgresql.log],[postgres],NaN,[parameters: $1 = '1666']
595,[<unnamed>],[database],[8.8.2],[Debian GNU/Linux],[histesting],[11461],"[02-42-46-2E-39-BD, 02-42-BC-54-9B-CD, 72-9C-5...",[hisdeploy_postgres_logs],[12 (bookworm)],[00000],...,[debian],[info],[/var/lib/docker/volumes/hisdeploy_postgres_lo...,[postgresql.log],[40128],[519313de-c266-4364-9197-6e99753b7294],[postgresql.log],[postgres],NaN,[parameters: $1 = '166666']